### ISSUE TITLE
Config data request failed

### ISSUE THREAD

**Issue by meymeynard** [vinsol-spree-contrib/spree-android#1]
Hello. I tried running the app and it always says this in the SplashActivity
```
11-06 23:43:29.030 2569-2569/com.vinsol.spree D/Spree: *** config data request failed
11-06 23:49:15.377 2569-7102/com.vinsol.spree D/OkHttp: --> GET /api/v1/config HTTP/1.1
11-06 23:49:15.378 2569-7102/com.vinsol.spree D/OkHttp: --> END GET
11-06 23:49:17.221 2569-2569/com.vinsol.spree D/Spree: *** config data request failed
```

Any comments?

**Comment by meymeynard** [comment]
We made an instance of the latest stable of the SpreeCommerce instead of using the Heroku instance you provided. (http://shop-spree.herokuapp.com/)

**Comment by vaishalok** [comment]
For this project, we are using customized version of Spree. 'config' endpoint is part of custom implementation and not of standard spree implementation. We have not open-sourced custom backend Spree implementation as of now, please let me know if you need the backend codebase and I can share that with you.

**Comment by vaishalok** [comment]
Backend code is now open source [here](https://github.com/vinsol-spree-contrib/shopspree-sales-app).
