### ISSUE TITLE
API path for default app 

### ISSUE THREAD

**Issue by kaustubhkabra** [vinsol-spree-contrib/spree-android#2]
Hi,
I have just cloned [SPREE](https://github.com/spree/spree) and sanbox app is running fine on localhost:3000. How can I access this deployed web site from my Eclipse project ? I tried "http://localhost:3000/api/ams/". Is there any specific command while starting rails server to deploy APIs for sandbox app ?
Thanks !

**Comment by kaustubhkabra** [comment]
Ruby - ruby 2.3.0
Rails -  4.2.4
I was able to get API working by correcting base project. I am able to hit documentation URL and documentation page shows up.
<img width="1399" alt="documentation" src="https://cloud.githubusercontent.com/assets/642690/22362254/521822ba-e487-11e6-8ab2-b398483bcabd.png">
However, GET api/ams/home got hit once and then it gave this error.
<img width="517" alt="home" src="https://cloud.githubusercontent.com/assets/642690/22362278/790355fc-e487-11e6-8e84-12b858b19756.png">
And, GET api/ams/products shows TCP connection error.
<img width="956" alt="products" src="https://cloud.githubusercontent.com/assets/642690/22362291/88fa1482-e487-11e6-9afd-6e1188d4d8e6.png">

Can someone help here on what is wrong ?

**Comment by nghiapdx** [comment]
@kaustubh-kabra put this code in your ~/app/models/spree/sales_app_configuration.rb

last_updated_state = Spree::Banner.where.not(updated_at: nil).order(updated_at: :desc).first
      if 
        last_updated_state && config.updated_at < last_updated_state.updated_at
        config.home_checksum = generate_home_checksum
        puts 'spree:Banner end if statement'
      end

**Comment by kaustubhkabra** [comment]
@nghiapdx Thanks !
