### ISSUE TITLE
Error java.lang.IndexOutOfBoundsException: Invalid index 3, size is 2

### ISSUE THREAD

**Issue by nghiapdx** [vinsol-spree-contrib/spree-android#3]
If I comment out the two lines 'taxonomies.remove' I then get Invalid index 0, size is 0. How do I make this work?

     private void setup(ArrayList<Taxonomy> taxonomies) {
        taxonomies.remove(3);
        taxonomies.remove(2);

        taxons.clear();
        for(Taxonomy taxonomy : taxonomies) {
            taxons.add(taxonomy.getRootTaxon());
        }

        page1.setup(getActivity(), taxons, this);
        actionButton.setState(MaterialMenuDrawable.IconState.X);
        currentPage = page1;
    }

**Comment by vaishalok** [comment]
Are you using test server or your own server?
I tested it using test server url and it is working fine.

**Comment by kaustubhkabra** [comment]
@nghiapdx Please see that you have taxonomies in your backend. 
Option 1 - You can add one using admin panel from your website.
Option 2 - Make android app code changes to consider no taxonomies at backend.

**Comment by nghiapdx** [comment]
The problem was Spree::Banner needed to be created in admin. But now the app stops compiling after loading all the US states.  What am I missing? 

>  D/Spree: *** State list received
>  W/art: Suspending all threads took: 15.956ms
>  I/art: Background sticky concurrent mark sweep GC freed 36805(1701KB) AllocSpace objects, 0(0B) LOS  objects, 25% free, 4MB/5MB, paused 22.367ms total 38.078ms
>  D/AndroidRuntime: Shutting down VM 
>  E/AndroidRuntime: FATAL EXCEPTION: main
>                    Process: com.vinsol.spree, PID: 3099
>                    java.lang.RuntimeException: Unable to start activity  ComponentInfo{com.vinsol.spree/com.vinsol.spree.controllers.Home}:  java.lang.IndexOutOfBoundsException: Invalid index 3, size is 2

**Comment by vaishalok** [comment]
It is crashing due to hardcoded values of taxons. i.e.
```
    taxonomies.remove(3);
    taxonomies.remove(2);
```
I have removed those lines and pushed the code. Try using updated code-base.

**Comment by nghiapdx** [comment]
The app works. Thank you so much for the update!
