### ISSUE TITLE
Taxons Elastic search failing

### ISSUE THREAD

**Issue by kaustubhkabra** [vinsol-spree-contrib/spree-android#4]
When I pick taxon based product search, below is the error thrown -

`{"exception":"[400] {\"error\":{\"root_cause\":[{\"type\":\"query_parsing_exception\",\"reason\":\"[multi_match] query does not support [taxons_name_in]\",\"index\":\"spree_1487101167265\",\"line\":1,\"col\":52}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"spree_1487101167265\",\"node\":\"XcfRqy1XT4ObgmdASh5UnA\",\"reason\":{\"type\":\"query_parsing_exception\",\"reason\":\"[multi_match] query does not support [taxons_name_in]\",\"index\":\"spree_1487101167265\",\"line\":1,\"col\":52}}]},\"status\":400}"}`

![screenshot_1487101681](https://cloud.githubusercontent.com/assets/642690/22955136/827bb808-f2e8-11e6-964c-c39ff655ec88.png)

Product search works fine though.

**Comment by vaishalok** [comment]
[Commit: Products by Taxons endpoint integrated](https://github.com/vinsol-spree-contrib/spree-android/commit/a9e23483b1c0dbaf476ec739656ec8bf24456414) should fix the issue.

**Comment by kaustubhkabra** [comment]
@vaishalok Thanks. This fixed it. But, number of records in result is limited to 10 even after sending per_page count to 20.

This is from server:
```
Started GET "/api/ams/products?page=1&per_page=20" for 73.85.190.24 at 2017-02-18 23:12:51 +0000
DEBUG: Chewy strategies stack: [2] <- atomic @ /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/railtie.rb:16
Processing by Spree::Api::Ams::ProductsController#index as */*
  Parameters: {"page"=>"1", "per_page"=>"20"}
  Spree::User Load (0.3ms)  SELECT  `spree_users`.* FROM `spree_users` WHERE `spree_users`.`deleted_at` IS NULL AND `spree_users`.`spree_api_key` = '' LIMIT 1
  SpreeIndex::Product Search (11.3ms) {:body=>{:query=>{:match_all=>{}}, :sort=>[{"name.untouched"=>:asc}, {"price"=>:asc}, {"available_on"=>:desc}]}, :index=>["spree"], :type=>["product"]}
  Spree::Product Load (0.3ms)  SELECT `spree_products`.* FROM `spree_products` WHERE `spree_products`.`deleted_at` IS NULL AND `spree_products`.`id` IN (28, 22, 17, 37, 19, 21, 23, 24, 31, 30)
  SpreeIndex::Product Search (4.7ms) {:body=>{:query=>{:match_all=>{}}, :sort=>[{"name.untouched"=>:asc}, {"price"=>:asc}, {"available_on"=>:desc}]}, :index=>["spree"], :type=>["product"]}
  CACHE (0.0ms)  SELECT `spree_products`.* FROM `spree_products` WHERE `spree_products`.`deleted_at` IS NULL AND `spree_products`.`id` IN (28, 22, 17, 37, 19, 21, 23, 24, 31, 30)
```

I think I am unable to find a way to send "size" parameter for Elastic search. Any suggestion on making api/ams change for getting more number of results ?

**Comment by kaustubhkabra** [comment]
Got it, solved using config changes.
