### ISSUE TITLE
Error:(343, 49) error: incompatible types: String cannot be converted to Context

### ISSUE THREAD

**Issue by nghiapdx** [vinsol-spree-contrib/spree-android#5]
Error pointing to this line in controllers/fragments/PaymentFragment.java
            Stripe stripe = new Stripe(Constants.STRIPE_APP_KEY);

All the imports are there, just like your source code on Github.

**Comment by vaishalok** [comment]
fixed [here](https://github.com/vinsol-spree-contrib/spree-android/commit/73a4129677998a034c3a1d9c6d824a77f573ff47)

**Comment by nghiapdx** [comment]
@vaishalok, you're the best. many thanks. -HNP
