### ISSUE TITLE
API configure issue

### ISSUE THREAD

**Issue by anukools** [vinsol-spree-contrib/spree-android#6]
Hi, Demo configure backend api url, deployed at heroku http://shop-spree.herokuapp.com/api/ams/ 
is not working. 
How to setup admin and get access to BASE_API_URL and BASE_URL.

**Comment by v4ibh4v** [comment]
Sample heroku server should work now. Please try again and let us know if you still face issues

**Comment by anukools** [comment]
![issue](https://cloud.githubusercontent.com/assets/8350658/26198771/001c0610-3be5-11e7-97ce-34d6eac0d10a.PNG)


Still getting this error. Do I need to register first. If Yes then please share the link for same.

**Comment by v4ibh4v** [comment]
[This](http://shop-spree.herokuapp.com/api/ams/) is the API URL 
Please use this in Constants.java 
public static final String BASE_API_URL = "YOUR SPREE BACKEND APP API URL";
You can see the storefront [here](http://shop-spree.herokuapp.com/)

**Comment by anukools** [comment]
Thanks and what is STRIPE_APP_KEY in constant file ..? 

FYI just add  below code where ever you are using <include> with some id. otherwise it is crashing.
" android:layout_width="wrap_content"
   android:layout_height="wrap_content""

**Comment by v4ibh4v** [comment]
Fixed the crash. 
Stripe is a payment gateway. Check it out [here](https://stripe.com/docs/mobile/android).
You will have to signup and create an app on Stripe to get stripe app key

**Comment by anukools** [comment]
Same issue is there in ProfileFragment update that also.

Thanks for info on payment gateway.

**Comment by anukools** [comment]
@v4ibh4v  Found Any solution for ProfileFragment view Crash...? happening in Android N.

**Comment by vaishalok** [comment]
Fixed in [this](https://github.com/vinsol-spree-contrib/spree-android/commit/73d9aa24c2146d1d5c56653ce38d088d8859c944) commit.
